# Generated by Django 4.0.2 on 2022-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_game_id_game_gid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
